baseURL: https://madalinadumitrescu.netlify.app/
languageCode: en-us
title: Portfolio website for Madalina Dumitrescu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      LBS Master in Analytics and Management Student 
    title: Madalina Dumitrescu
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park, London NW1 4SA
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mdumitrescu.mam2023@london.edu
        title: Email
    enable: yes
    #phone:
      #- phone: (000) 000-0000 x1234
      #  title: Phone
  custom_css: []
  custom_js: []
  description: My description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      # label: Twitter
      #  url: https://www.twitter.com
      #- icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      #- icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/madalinad28
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/madalina-dumitrescu/
  name: Madalina Dumitrescu
  navigation:
    button1:
      - name: Projects
        url: projects
    button2:
      - name: Download CV
        url: files/cv_madalina_dumitrescu.pdf
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/about_me
      - name: Education
        url: blogs/education
      - name: Professional Experience
        url: blogs/professional_experience
      - name: Additional Information
        url: blogs/additional_information
    menu: Menu
    subtitle: Madalina Dumitrescu
    title: Projects Portoflio
  tiles:
    enable: yes
    showcase:
      - image: gender.jpg
        subtitle: Project 1
        title: Gender Pay Gap - Mith or Fact Analysis
        url: projects/project1
      - image: imdb..png
        subtitle: Project 2
        title: IMDB Movies Analysis
        url: projects/project2
      - image: bikes.jpg
        subtitle: Project 3
        title: TFL Strikes Influence on Bike Rentals
        url: projects/project3
      - image: energy.jpg
        subtitle: Project 4
        title: Renewable Energy Consumption in the World
        url: projects/project4
      
    
  two:
    buttonText: About Me
    enable: yes
    title: Find out more about me
    url: blogs
